services:
  webhook:
    container_name: deploy_webhook
    build: .
    ports:
      - "57021:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=production
