services:
  webhook:
    container_name: deploy_webhook
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "57021:3000"
    volumes:
      - .:/app
      - ./deploy_script.sh:/deploy_script.sh:ro
    command: npm run start
