services:
  webhook:
    container_name: deploy_webhook
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "57021:3000"
    volumes:
      - .:/app
      # - /app/node_modules
    command: npm run start
